/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Tue Mar 31 14:13:30 2026


#ifndef VOICEBOXSYNTHESIZER_PARAMSPARSER_H
#define VOICEBOXSYNTHESIZER_PARAMSPARSER_H

#include <yarp/os/Searchable.h>
#include <yarp/dev/IDeviceDriverParams.h>
#include <string>
#include <cmath>

/**
* This class is the parameters parser for class VoiceBoxSynthesizer.
*
* These are the used parameters:
* | Group name | Parameter name | Type   | Units | Default Value | Required | Description                           | Notes                                                                                                                                           |
* |:----------:|:--------------:|:------:|:-----:|:-------------:|:--------:|:-------------------------------------:|:-----------------------------------------------------------------------------------------------------------------------------------------------:|
* | -          | base_ip        | string | -     | localhost     | 0        | The ip address of the voiceBox server | -                                                                                                                                               |
* | -          | base_port      | string | -     | 17493         | 0        | The port for the voicebox address     | -                                                                                                                                               |
* | -          | voice          | string | -     | -             | 1        | The name of the voice profile         | To check the available profiles, either check in the VoiceBox app or use the following command: curl http://server_ip_addr:server_port/profiles |
*
* The device can be launched by yarpdev using one of the following examples (with and without all optional parameters):
* \code{.unparsed}
* yarpdev --device voiceBoxSynthesizer --base_ip localhost --base_port 17493 --voice <mandatory_value>
* \endcode
*
* \code{.unparsed}
* yarpdev --device voiceBoxSynthesizer --voice <mandatory_value>
* \endcode
*
*/

class VoiceBoxSynthesizer_ParamsParser : public yarp::dev::IDeviceDriverParams
{
public:
    VoiceBoxSynthesizer_ParamsParser();
    ~VoiceBoxSynthesizer_ParamsParser() override = default;

public:
    const std::string m_device_classname = {"VoiceBoxSynthesizer"};
    const std::string m_device_name = {"voiceBoxSynthesizer"};
    bool m_parser_is_strict = false;
    struct parser_version_type
    {
         int major = 2;
         int minor = 0;
    };
    const parser_version_type m_parser_version = {};

    std::string m_provided_configuration;

    const std::string m_base_ip_defaultValue = {"localhost"};
    const std::string m_base_port_defaultValue = {"17493"};
    const std::string m_voice_defaultValue = {""};

    std::string m_base_ip = {"localhost"};
    std::string m_base_port = {"17493"};
    std::string m_voice = {}; //This default value is autogenerated. It is highly recommended to provide a suggested value also for mandatory parameters.

    bool          parseParams(const yarp::os::Searchable & config) override;
    std::string   getDeviceClassName() const override { return m_device_classname; }
    std::string   getDeviceName() const override { return m_device_name; }
    std::string   getDocumentationOfDeviceParams() const override;
    std::vector<std::string> getListOfParams() const override;
    bool getParamValue(const std::string& paramName, std::string& paramValue) const override;
    std::string   getConfiguration() const override;
};

#endif
