/*
 * SPDX-FileCopyrightText: 2023-2023 Istituto Italiano di Tecnologia (IIT)
 * SPDX-License-Identifier: LGPL-2.1-or-later
 */


// Generated by yarpDeviceParamParserGenerator (2.0)
// This is an automatically generated file. Please do not edit it.
// It will be re-generated if the cmake flag ALLOW_DEVICE_PARAM_PARSER_GERNERATION is ON.

// Generated on: Tue Mar 31 14:13:30 2026


#include "VoiceBoxSynthesizer_ParamsParser.h"
#include <yarp/os/LogStream.h>
#include <yarp/os/Value.h>

namespace {
    YARP_LOG_COMPONENT(VoiceBoxSynthesizerParamsCOMPONENT, "yarp.device.VoiceBoxSynthesizer")
}


VoiceBoxSynthesizer_ParamsParser::VoiceBoxSynthesizer_ParamsParser()
{
}


std::vector<std::string> VoiceBoxSynthesizer_ParamsParser::getListOfParams() const
{
    std::vector<std::string> params;
    params.push_back("base_ip");
    params.push_back("base_port");
    params.push_back("voice");
    return params;
}


bool VoiceBoxSynthesizer_ParamsParser::getParamValue(const std::string& paramName, std::string& paramValue) const
{
    if (paramName =="base_ip")
    {
        paramValue = m_base_ip;
        return true;
    }
    if (paramName =="base_port")
    {
        paramValue = m_base_port;
        return true;
    }
    if (paramName =="voice")
    {
        paramValue = m_voice;
        return true;
    }

    yError() <<"parameter '" << paramName << "' was not found";
    return false;

}


std::string VoiceBoxSynthesizer_ParamsParser::getConfiguration() const
{
    //This is a sub-optimal solution.
    //Ideally getConfiguration() should return all parameters but it is currently
    //returning only user provided parameters (excluding default values)
    //This behaviour will be fixed in the near future.
    std::string s_cfg = m_provided_configuration;
    return s_cfg;
}

bool      VoiceBoxSynthesizer_ParamsParser::parseParams(const yarp::os::Searchable & config)
{
    //Check for --help option
    if (config.check("help"))
    {
        yCInfo(VoiceBoxSynthesizerParamsCOMPONENT) << getDocumentationOfDeviceParams();
    }

    m_provided_configuration = config.toString();
    yarp::os::Property prop_check(m_provided_configuration.c_str());
    //Parser of parameter base_ip
    {
        if (config.check("base_ip"))
        {
            m_base_ip = config.find("base_ip").asString();
            yCInfo(VoiceBoxSynthesizerParamsCOMPONENT) << "Parameter 'base_ip' using value:" << m_base_ip;
        }
        else
        {
            yCInfo(VoiceBoxSynthesizerParamsCOMPONENT) << "Parameter 'base_ip' using DEFAULT value:" << m_base_ip;
        }
        prop_check.unput("base_ip");
    }

    //Parser of parameter base_port
    {
        if (config.check("base_port"))
        {
            m_base_port = config.find("base_port").asString();
            yCInfo(VoiceBoxSynthesizerParamsCOMPONENT) << "Parameter 'base_port' using value:" << m_base_port;
        }
        else
        {
            yCInfo(VoiceBoxSynthesizerParamsCOMPONENT) << "Parameter 'base_port' using DEFAULT value:" << m_base_port;
        }
        prop_check.unput("base_port");
    }

    //Parser of parameter voice
    {
        if (config.check("voice"))
        {
            m_voice = config.find("voice").asString();
            yCInfo(VoiceBoxSynthesizerParamsCOMPONENT) << "Parameter 'voice' using value:" << m_voice;
        }
        else
        {
            yCError(VoiceBoxSynthesizerParamsCOMPONENT) << "Mandatory parameter 'voice' not found!";
            yCError(VoiceBoxSynthesizerParamsCOMPONENT) << "Description of the parameter: The name of the voice profile";
            return false;
        }
        prop_check.unput("voice");
    }

    /*
    //This code check if the user set some parameter which are not check by the parser
    //If the parser is set in strict mode, this will generate an error
    if (prop_check.size() > 0)
    {
        bool extra_params_found = false;
        for (auto it=prop_check.begin(); it!=prop_check.end(); it++)
        {
            if (m_parser_is_strict)
            {
                yCError(VoiceBoxSynthesizerParamsCOMPONENT) << "User asking for parameter: "<<it->name <<" which is unknown to this parser!";
                extra_params_found = true;
            }
            else
            {
                yCWarning(VoiceBoxSynthesizerParamsCOMPONENT) << "User asking for parameter: "<< it->name <<" which is unknown to this parser!";
            }
        }

       if (m_parser_is_strict && extra_params_found)
       {
           return false;
       }
    }
    */
    return true;
}


std::string      VoiceBoxSynthesizer_ParamsParser::getDocumentationOfDeviceParams() const
{
    std::string doc;
    doc = doc + std::string("\n=============================================\n");
    doc = doc + std::string("This is the help for device: VoiceBoxSynthesizer\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("This is the list of the parameters accepted by the device:\n");
    doc = doc + std::string("'base_ip': The ip address of the voiceBox server\n");
    doc = doc + std::string("'base_port': The port for the voicebox address\n");
    doc = doc + std::string("'voice': The name of the voice profile\n");
    doc = doc + std::string("\n");
    doc = doc + std::string("Here are some examples of invocation command with yarpdev, with all params:\n");
    doc = doc + " yarpdev --device voiceBoxSynthesizer --base_ip localhost --base_port 17493 --voice <mandatory_value>\n";
    doc = doc + std::string("Using only mandatory params:\n");
    doc = doc + " yarpdev --device voiceBoxSynthesizer --voice <mandatory_value>\n";
    doc = doc + std::string("=============================================\n\n");    return doc;
}
